# Generated by Django 5.0.3 on 2024-05-09 17:16

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=11)),
                ('Password', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('Firstname', models.CharField(max_length=15)),
                ('Lastname', models.CharField(max_length=15)),
                ('Middlename', models.CharField(blank=True, max_length=15)),
                ('Email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('Phone',), name='unique_phone'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('Email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('Phone__startswith', '0')), name='check_phone'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('birthdate__lte', django.db.models.expressions.CombinedExpression(models.F('birthdate'), '-', models.Value(datetime.timedelta(days=14))))), name='check_birthdate'),
        ),
    ]
