# Generated by Django 5.0.3 on 2024-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_ads_categoriestag_categoriestypes_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesTag',
            new_name='IdCategoriesTypesIdTag',
        ),
        migrations.AlterUniqueTogether(
            name='idcategoriestypesidtag',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AddConstraint(
            model_name='idcategoriestypesidtag',
            constraint=models.UniqueConstraint(fields=('idcategories', 'idtag'), name='unique_idcategories_idtag'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('Phone__isnull', False), models.Q(('Phone', ''), _negated=True)), name='check_phone'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('birthdate__isnull', False), models.Q(('birthdate__lte', '2008-01-01'), ('birthdate__gte', '2008-01-01'), _connector='OR')), name='check_birthdate'),
        ),
        migrations.AlterModelTable(
            name='ads',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categoriestypes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='idcategoriestypesidtag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicetypes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
